### PR TITLE
Sync for all components not only interfaces

### LINKED ISSUE #3: Extend module to support other "components"
While this seems to be an fantastic plugin, to sync network interface from device template to actual device, in a controlled manner..:) - there are also other components in a device template.
Do you have plans to extend the plugin to support other "components"?

### PR DESCRIPTION
**Pull request by rizlas**
Hi,
first of all thank you for your plugin. I made a fork of it and added the possibility to sync all NetBox components. I tested it with NetBox 3.1.5 and it is entirely working.
I mainly used your business logic, but the quality of the code can still be improved as there are repeating or decentralized pieces of code (example: `PowerOutletComparisonView`, `FrontPortComparisonView`). I also changed the table rendering using bootstrap 5 and by removing the double table. The comparison of the objects is now done on all fields and not only on the name, you can see in detail in `comparison.py`.
Added a new variable that allows you to choose whether to display the interface summary panel or not.

Further renaming changes are needed for consistency, as the plugin no longer includes just interfaces, but I leave these changes to you.

This upgrade closes #3

Thank you

### CODE REVIEW

**Comment by drygdryg** [comment]
I will review this shortly and accept

**Comment by rizlas** [comment]
Thank you, I developed in a hurry and as I said the quality of the code should/must be improved. Anyway I'm here if you want me to modify something before closing the PR.

**Comment by drygdryg** [comment]
Thank you for your hard work! It would be nice to add the ability to compare components, ignoring their descriptions. This could be an option in the `PLUGINS_CONFIG`.

**Comment by rizlas** [comment]
Hi,
I implemented it and tested. Seems ok. If `compare_description` is True, description is also synced to device otherwise not.

For default value, pick whatever you like :-) 

Thank you!

**Comment by drygdryg** [comment]
Thank you for your contribution!

**Comment by rizlas** [comment]
Thanks to you, looking forward for the new release

**Comment by AnythingOverIP** [comment]
When will we have the chance to have this included in a release?

**Comment by rizlas** [comment]
You can use my fork if you want.. Its been two years, I don't know if it will ever be released

**Pull request merged**
